// src/utils/countryCodes.js

const countryNameToCodeMap = {
  Afghanistan: 'af',
  Albania: 'al',
  Algeria: 'dz',
  Andorra: 'ad',
  Angola: 'ao',
  Argentina: 'ar',
  Australia: 'au',
  Austria: 'at',
  Bangladesh: 'bd',
  Belgium: 'be',
  Belize: 'bz',
  Bhutan: 'bt',
  Bolivia: 'bo',
  Brazil: 'br',
  Bulgaria: 'bg',
  Cambodia: 'kh',
  Cameroon: 'cm',
  Canada: 'ca',
  Chile: 'cl',
  China: 'cn',
  Colombia: 'co',
  "Costa Rica": 'cr',
  Croatia: 'hr',
  Cuba: 'cu',
  Czechia: 'cz',
  Denmark: 'dk',
  "Dominican Republic": 'do',
  Ecuador: 'ec',
  Egypt: 'eg',
  "El Salvador": 'sv',
  Estonia: 'ee',
  Finland: 'fi',
  France: 'fr',
  Germany: 'de',
  Ghana: 'gh',
  Greece: 'gr',
  Guatemala: 'gt',
  Honduras: 'hn',
  Hungary: 'hu',
  Iceland: 'is',
  India: 'in',
  Indonesia: 'id',
  Iran: 'ir',
  Iraq: 'iq',
  Ireland: 'ie',
  Israel: 'il',
  Italy: 'it',
  Jamaica: 'jm',
  Japan: 'jp',
  Jordan: 'jo',
  Kazakhstan: 'kz',
  Kenya: 'ke',
  Kuwait: 'kw',
  Laos: 'la',
  Latvia: 'lv',
  Lebanon: 'lb',
  Liberia: 'lr',
  Lithuania: 'lt',
  Luxembourg: 'lu',
  Madagascar: 'mg',
  Malaysia: 'my',
  Mali: 'ml',
  Malta: 'mt',
  Mexico: 'mx',
  Moldova: 'md',
  Monaco: 'mc',
  Mongolia: 'mn',
  Montenegro: 'me',
  Morocco: 'ma',
  Mozambique: 'mz',
  Myanmar: 'mm',
  Namibia: 'na',
  Nepal: 'np',
  Netherlands: 'nl',
  "New Zealand": 'nz',
  Nicaragua: 'ni',
  Nigeria: 'ng',
  "North Korea": 'kp',
  Norway: 'no',
  Oman: 'om',
  Pakistan: 'pk',
  Panama: 'pa',
  Paraguay: 'py',
  Peru: 'pe',
  Philippines: 'ph',
  Poland: 'pl',
  Portugal: 'pt',
  Qatar: 'qa',
  Romania: 'ro',
  Russia: 'ru',
  "Saudi Arabia": 'sa',
  Senegal: 'sn',
  Serbia: 'rs',
  Singapore: 'sg',
  Slovakia: 'sk',
  Slovenia: 'si',
  Somalia: 'so',
  "South Africa": 'za',
  "South Korea": 'kr',
  Spain: 'es',
  "Sri Lanka": 'lk',
  Sudan: 'sd',
  Sweden: 'se',
  Switzerland: 'ch',
  Syria: 'sy',
  Taiwan: 'tw',
  Tanzania: 'tz',
  Thailand: 'th',
  Tunisia: 'tn',
  Turkey: 'tr',
  Uganda: 'ug',
  Ukraine: 'ua',
  "United Arab Emirates": 'ae',
  "United Kingdom": 'gb',
  "United States": 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Venezuela: 've',
  Vietnam: 'vn',
  Yemen: 'ye',
  Zambia: 'zm',
  Zimbabwe: 'zw',
};

export function countryNameToCode(name) {
  if (!name || typeof name !== 'string') return '';
  return countryNameToCodeMap[name.trim()] || '';
}

export function getFlagEmoji(countryCode) {
  if (!countryCode || countryCode.length !== 2) return '';
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt());
  return String.fromCodePoint(...codePoints);
}
